spring:
  data:
    cassandra:
      keyspace-name: main
      username: gUtzGDvdhHmSPMBJHhhbfqaF
      password: iz34bk9YTyALYg7_gPuD2MH5T+DKczt,eZWUMh.CZouH7h1A.X4rvC2+_3gs3rAezk.pZUZD,qnlz3wickSuHdNqhT6khyB14eb4iBawQjJm1-Dkuig-bXfB1Bg0ZS-w
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: 3e056837-a6a9-48bc-b9a8-e15c736bffac
  region: asia-south1
  keyspace: main
  application.token: AstraCS:gUtzGDvdhHmSPMBJHhhbfqaF:0db9700c6cc477a1a3574cc6966697768d82c89fed11976207c44ffa2b54a6f0


