spring:
  data:
    cassandra:
      keyspace-name: profile_manager
      schema-action: CREATE_IF_NOT_EXISTS
      request.timeout: 10s
      connect-timeout: 10s
      init-query-timeout: 10s
      local-datacenter: datacenter1
      contactpoints: http://localhost
      port: 9042
